In [31]:
# from google.colab import drive
# import os
# drive.mount('/content/drive/')
# os.chdir('/content/drive/My Drive/Colab Notebooks/Other_Files/')

# Load, Display, Save

In [2]:
import numpy as np
import cv2

## Load an image

In [33]:
img1 = cv2.imread('./images/flemingo.jpg')

In [34]:
print(img1)

[[[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 ...

 [[167 134  88]
  [167 134  88]
  [167 134  88]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]

 [[171 141  94]
  [171 141  94]
  [172 142  95]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]

 [[177 147 100]
  [177 147 100]
  [178 148 101]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]]


In [35]:
img1.shape

(640, 640, 3)

## Display an image

In [36]:
cv2.imshow('example',img1)
cv2.waitKey(10000) # millseconds
cv2.destroyAllWindows()

In [37]:
cv2.imshow('example',img1)
cv2.waitKey(0) # 0 is the special value that means "forever"
cv2.destroyAllWindows()

## Save an image

In [43]:
cv2.imwrite('./images/example.png',img1)

True

# Convert Color

## Color Space

In [39]:
b,g,r = cv2.split(img1)

In [40]:
b

array([[188, 189, 189, ..., 188, 188, 188],
       [188, 189, 189, ..., 188, 188, 188],
       [188, 189, 189, ..., 188, 188, 188],
       ...,
       [167, 167, 167, ..., 177, 177, 177],
       [171, 171, 172, ..., 177, 177, 177],
       [177, 177, 178, ..., 177, 177, 177]], dtype=uint8)

In [41]:
cv2.imshow('color',img1)
cv2.imshow('blue',b)
cv2.imshow('red',r)
cv2.imshow('green',g)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Color Converter

In [44]:
img1_rgb = cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)

In [46]:
img1_rgb

array([[[119, 163, 188],
        [120, 164, 189],
        [120, 164, 189],
        ...,
        [119, 163, 188],
        [119, 163, 188],
        [119, 163, 188]],

       [[119, 163, 188],
        [120, 164, 189],
        [120, 164, 189],
        ...,
        [119, 163, 188],
        [119, 163, 188],
        [119, 163, 188]],

       [[119, 163, 188],
        [120, 164, 189],
        [120, 164, 189],
        ...,
        [119, 163, 188],
        [119, 163, 188],
        [119, 163, 188]],

       ...,

       [[ 88, 134, 167],
        [ 88, 134, 167],
        [ 88, 134, 167],
        ...,
        [ 98, 144, 177],
        [ 98, 144, 177],
        [ 98, 144, 177]],

       [[ 94, 141, 171],
        [ 94, 141, 171],
        [ 95, 142, 172],
        ...,
        [ 98, 144, 177],
        [ 98, 144, 177],
        [ 98, 144, 177]],

       [[100, 147, 177],
        [100, 147, 177],
        [101, 148, 178],
        ...,
        [ 98, 144, 177],
        [ 98, 144, 177],
        [ 98, 144, 177]]

In [47]:
# grayscale
gray = cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)

In [48]:
gray

array([[153, 154, 154, ..., 153, 153, 153],
       [153, 154, 154, ..., 153, 153, 153],
       [153, 154, 154, ..., 153, 153, 153],
       ...,
       [124, 124, 124, ..., 134, 134, 134],
       [130, 130, 131, ..., 134, 134, 134],
       [136, 136, 137, ..., 134, 134, 134]], dtype=uint8)

In [49]:
cv2.imshow('color_bgr',img1)
cv2.imshow('color_rgb',img1_rgb)
cv2.imshow('gray',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [50]:
cv2.imwrite('./images/GRAY.png',gray)

True

# Accessing And Manipulate Pixels

In [3]:
img2 = cv2.imread('./images/bird.jpg')

In [4]:
def display(winname,image):
    cv2.imshow(winname,image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [5]:
display('winname',img2)

In [6]:
img2.shape

(681, 640, 3)

In [7]:
type(img2)

numpy.ndarray

In [10]:
# acess first 100 rows and 100 columns
corners = img2[0:100,0:100]

In [11]:
display('corner',corners)

In [12]:
cv2.imshow('original',img2)
cv2.imshow('cornor',corners)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# change first 100 rows and 100 columns to green color
green = (0,255,0)
img2[0:100,0:100] = green

In [15]:
display('manipulate',img2)